spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria
    username: postgres
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    #properties:
    #  hibernate:
    #    show_sql: true
logging:
  level:
    org.springframework.security.web.*: debug